# Generated by Django 4.0.6 on 2022-11-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clients_queansfile_alter_useravatar_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
