# Generated by Django 4.1 on 2022-11-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_user_type'),
    ]

    operations = [

    ]
