# Generated by Django 4.1 on 2022-11-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clients_is_deleted_coaches_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
