# Generated by Django 3.2.14 on 2022-12-12 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_participant_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
