# Generated by Django 4.0.6 on 2022-11-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confidentialquestions',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='confidentialquestions',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='confidentialquestions',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='editedconfidentialanswer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='editedconfidentialanswer',
            name='prevanswer',
        ),
        migrations.RemoveField(
            model_name='editedconfidentialanswer',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='editedconfidentialanswer',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='is_confidential',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ConfidentialAnswer',
        ),
        migrations.DeleteModel(
            name='ConfidentialQuestions',
        ),
        migrations.DeleteModel(
            name='EditedConfidentialAnswer',
        ),
    ]
