# Generated by Django 4.0.6 on 2022-11-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_confidentialquestions_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveycampaign',
            name='expires',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
